### ISSUE TITLE
SyntaxError: Unexpected token U in JSON

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#10]
# Package Versions #
Replace the values below using the output from storjshare --version.

2.0.1

Replace the values below using the output from node --version.

v6.9.4

OS: windows 10

# Expected Behavior #

Start running the daemon.

# Actual Behavior #

Try to run the generated config results in an error.

```
C:\Users\Meije>storjshare start --config C:\Users\Meije\storjshare\config.json
undefined:56
  "loggerOutputFile": "C:\Users\Meije\.config\storjshare\logs\72d6daaa086a7e25d53c58234d03bf9594b78590.log",
                          ^

SyntaxError: Unexpected token U in JSON at position 732
    at Object.parse (native)
    at exports.parse (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\lib\utils.js:15:17)
    at addConfigFile (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\index.js:31:20)
    at module.exports (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\index.js:47:20)
    at Object.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\lib\config\daemon.js:16:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

C:\Users\Meije>

```

# Steps to Reproduce #

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Generate the config.
Try to run the generated config.

**Comment by MeijeSibbel** [comment]
Config file issue:  
```
// Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid].log
  "loggerOutputFile": "E:\\StorjCLI",
  // Directory path to store contracts and shards
  "storagePath": "E:\\StorjCLI",
```

**Comment by bookchin** [comment]
Yes double slash is required, you must wrap paths in quotes on windows or the shell will strip them before passing to program
