### ISSUE TITLE
if no favorite editor crashes

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-daemon#101]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.5.1
```

Replace the values below using the output from `node --version`.

```
6.10.0
```

### Expected Behavior

Please describe the program's expected behavior.

When you run storjshare create --sjcx xxx   it is by default supposed to open in your favorite text editor..  If none is configured it crashes

root@1ce1e4b578f6:/# storjshare create --sjcx xxxxx

  * configuration written to /root/.config/storjshare/configs/74e809f73e4c682c8c53cab3deee4fd96df620d4.json
  * opening in your favorite editor to tweak before running
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
root@1ce1e4b578f6:/# storjshare create --sjcx xxx 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
run storjshare create --sjcx xxxxx

it should open in the favorite text editor (or a default one) but instead crashes with this

root@1ce1e4b578f6:/# storjshare create --sjcx xxxxx

  * configuration written to /root/.config/storjshare/configs/74e809f73e4c682c8c53cab3deee4fd96df620d4.json
  * opening in your favorite editor to tweak before running
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
root@1ce1e4b578f6:/# storjshare create --sjcx xxxx 

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1.Run ubuntu 16.10
2. Run storjshare create --sjcx xxxxx

Error produces

**Comment by njj** [comment]
I'm having this issue as well, any updates? @computeronix
