### ISSUE TITLE
Error: Cannot find module 'weak'

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#11]
# Package Versions #
Replace the values below using the output from storjshare --version.

2.0.1

Replace the values below using the output from node --version.

v6.9.4

OS: windows 10

# Expected Behavior #

Start running the daemon.

# Actual Behavior #

Try to run the generated config results in an error.

```
C:\Users\Meije>storjshare start --config E:\StorjCLI\config.json

  * daemon is not running, starting...
module.js:471
    throw err;
    ^

Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new D (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode\index.js:28:20)
    at Function.exports.connect (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode\index.js:12:13)
    at Object.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\bin\storjshare-start.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

C:\Users\Meije>

```

# Steps to Reproduce #

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Generate a new config.
Try to run the generated config.

**Comment by bookchin** [comment]
The `weak` package did not get built, make sure npm install doesn't fail and that you have the build deps.
