### ISSUE TITLE
Share terminates with error "Can't set headers after they are sent."

### ISSUE THREAD

**Issue by ordtrogen** [Storj/storjshare-daemon#127]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v7.10.0
```

### Expected Behavior

Share should continue to run indefinately

### Actual Behavior

After updating to 2.5.3, one of my shares stops after about 15 minutes. The corresponding log says

```
[...]
{"level":"info","message":"replying to message to 1c743e57f0d76efe3543353b16aba7e74f0d8405","timestamp":"2017-05-07T07:40:39.293Z"}
{"level":"warn","message":"rpc call 3aad549f062b0eadb8f609d94620d052d9026481 timed out","timestamp":"2017-05-07T07:40:39.333Z"}
{"level":"info","message":"replying to message to cc02f3f2dc50196c9723668d77efccc8ccd980f2","timestamp":"2017-05-07T07:40:39.334Z"}
_http_outgoing.js:371
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.format (/usr/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:147:10)
    at ServerResponse.send (/usr/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:340:14)
    at Transport._send (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/transport.js:247:45)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:187:12
    at Transport.RPC._trigger (/usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:297:12)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:173:10
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:309:5
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:251:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:154:25
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:612:34
    at FarmerInterface.Network._signMessage (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:492:3)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:146:13)

```

**Comment by littleskunk** [comment]
Nodejs v7.10.0 is not supported. Please install nodejs lts (v6.10.3 at the moment).

Close please.

**Comment by theretohere** [comment]
I am seeing my nodes stop about once a day with a similar error. My node --version returns v6.11.1, so the same major revision as recommended in the ticket.


Here's the last lines of the log of a node that stopped by itself right after this error today:

{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"6.8.0\",\"protocol\":\"1.1.0\",\"address\":\"stor1.storjlt.xyz\",\"port\":7507,\"nodeID\":\"39f4cbc548a3872215d5b4675d9ac8ff8f0a0b3a\",\"lastSeen\":1502156961103}","timestamp":"2017-08-08T01:49:36.620Z"}
_http_outgoing.js:367
throw new Error('Can\'t set headers after they are sent.');
^

Error: Can't set headers after they are sent.
at ServerResponse.setHeader (_http_outgoing.js:367:11)
at ServerResponse.format (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:147:10)
at ServerResponse.send (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:340:14)
at ReadableFileStream._handleReadFailure (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\shard-server.js:257:11)
at emitOne (events.js:96:13)
at ReadableFileStream.emit (events.js:188:7)
at _sBucket._db.get (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\read-stream.js:57:23)

**Comment by Hypocritus** [comment]
I am seeing this error as well.

```
"level":"error","message":"failed to relay publication to random neighbor {\"userAgent\":\"8.7.2\",\"protocol\":\"1.2.0\",\"address\":\"a.sgbcl.com\",\"port\":36674,\"nodeID\":\"f1e5857daba0756d84862185643fe6cfc6866360\",\"lastSeen\":1535043494970} with topic \"0e01\", reason: outgoing PUBLISH message has expired","timestamp":"2018-08-23T16:58:15.227Z"}
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.format (/home/robbie/.nvm/versions/node/v8.11.3/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:147:10)
    at ServerResponse.send (/home/robbie/.nvm/versions/node/v8.11.3/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:345:14)
    at ReadableFileStream._handleReadFailure (/home/robbie/.nvm/versions/node/v8.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:423:13)
    at emitOne (events.js:116:13)
    at ReadableFileStream.emit (events.js:211:7)
    at _sBucket._db.get (/home/robbie/.nvm/versions/node/v8.11.3/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/read-stream.js:57:23)

````
