### ISSUE TITLE
Unhandled 'error' event EHOSTUNREACH

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-daemon#128]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
* daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

No Error

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"received PING from 2f4cd0e8be4e6374a1ff77a4d4d169653a1e0c6b, sending PONG","timestamp":"2017-05-08T13:23:39.662Z"}
{"level":"info","message":"replying to message to 178c5858a0e1a504406920940b1ed75f379e3329","timestamp":"2017-05-08T13:23:39.662Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"204.12.214.226\",\"port\":4271,\"nodeID\":\"67c2dbd7ea608c3d79907c5d307bc2955a25ecd0\",\"lastSeen\":1494211078653}","timestamp":"2017-05-08T13:23:39.875Z"}
{"level":"info","message":"received FIND_NODE from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"204.12.214.226\",\"port\":4271,\"nodeID\":\"67c2dbd7ea608c3d79907c5d307bc2955a25ecd0\",\"lastSeen\":1494211078653}","timestamp":"2017-05-08T13:23:39.876Z"}
{"level":"info","message":"replying to message to c044eece1ba7047a8e594cf82db990077fce4d55","timestamp":"2017-05-08T13:23:39.876Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"68.9.88.143\",\"port\":4005,\"nodeID\":\"3e8de9c2dbea8c1b84ae3c24c66c504a63787722\",\"lastSeen\":1494213208792}","timestamp":"2017-05-08T13:23:40.073Z"}
{"level":"info","message":"received FIND_NODE from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"68.9.88.143\",\"port\":4005,\"nodeID\":\"3e8de9c2dbea8c1b84ae3c24c66c504a63787722\",\"lastSeen\":1494213208792}","timestamp":"2017-05-08T13:23:40.073Z"}
{"level":"info","message":"replying to message to 4339b1da4254b4dae609728143bc7037589fad2a","timestamp":"2017-05-08T13:23:40.074Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"004m.storjlt.xyz\",\"port\":4100,\"nodeID\":\"421d5a1fa65da88e1f6051197eabf9b6bae33abb\",\"lastSeen\":1494249628099}","timestamp":"2017-05-08T13:23:40.114Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"71.165.245.156\",\"port\":4007,\"nodeID\":\"423c4863a562a682cded332e9b20122b639b2558\",\"lastSeen\":1494249816180}","timestamp":"2017-05-08T13:23:40.115Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"storj.chadaustin.org\",\"port\":20387,\"nodeID\":\"42e41768c8b392b624b0a5e86af5f549d3fdf0df\",\"lastSeen\":1494249817334}","timestamp":"2017-05-08T13:23:40.131Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"6.3.2\",\"protocol\":\"1.1.0\",\"address\":\"78.94.95.122\",\"port\":41945,\"nodeID\":\"4209d3cbe50bf037df98cdc2fc14c9b4499f6418\",\"lastSeen\":1494249789361}","timestamp":"2017-05-08T13:23:40.144Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.3.2\",\"protocol\":\"1.1.0\",\"address\":\"78.94.95.122\",\"port\":41945,\"nodeID\":\"4209d3cbe50bf037df98cdc2fc14c9b4499f6418\",\"lastSeen\":1490053397608}","timestamp":"2017-05-08T13:23:40.405Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"71.165.245.156\",\"port\":4007,\"nodeID\":\"423c4863a562a682cded332e9b20122b639b2558\",\"lastSeen\":1493966616709}","timestamp":"2017-05-08T13:23:40.457Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read EHOSTUNREACH
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2017-05-08T13:23:43.566Z"}
{"level":"info","message":"node created with nodeID 42d1125aef7df4ce2e4777550afbeee01aee3877","timestamp":"2017-05-08T13:23:43.576Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: 13 ms","timestamp":"2017-05-08T13:23:43.599Z"}
{"level":"info","message":"resolving seeds from https://api.storj.io","timestamp":"2017-05-08T13:23:43.600Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.3.2\",\"protocol\":\"1.1.0\",\"address\":\"84.237.229.145\",\"port\":4000,\"nodeID\":\"47919b1ade7b2020341ba8916aadc83e5932deae\",\"lastSeen\":1493371552927}","timestamp":"2017-05-08T13:23:43.773Z"}
{"level":"info","message":"received PING from 47919b1ade7b2020341ba8916aadc83e5932deae, sending PONG","timestamp":"2017-05-08T13:23:43.777Z"}
{"level":"info","message":"replying to message to 09fcb9d15c184ef3cbffd47b0e29133803a78cc1","timestamp":"2017-05-08T13:23:43.777Z"}
{"level":"info","message":"routing HTTP request to proxy","timestamp":"2017-05-08T13:23:43.806Z"}
{"level":"warn","message":"no proxy with id 53ce2197bfda2b58bc4be2e25190c7500e87ffac exists","timestamp":"2017-05-08T13:23:43.806Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.2\",\"protocol\":\"1.1.0\",\"address\":\"frankii93.ddns.net\",\"port\":4000,\"nodeID\":\"235ba39a081e54b4d59190ac20083d9ee872c6a3\",\"lastSeen\":1494249500038}","timestamp":"2017-05-08T13:23:43.973Z"}'
```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/676

Close please.
