### ISSUE TITLE
Failed to get port, reason: listen EACCES

### ISSUE THREAD

**Issue by Anderseta** [Storj/storjshare-daemon#134]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.5.3, core: 6.4.2, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Actual Behavior

```
{"level":"error","message":"failed to get port, reason: listen EACCES 0.0.0.0:25","timestamp":"2017-05-09T22:19:10.208Z"}
Unhandled rejection Error: listen EACCES 0.0.0.0:25
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### Steps to Reproduce

```
This seems to be happening on port 25, it might be this conf:

"tunnelGatewayRange": {
    "min": 25,
    "max": 50000
  }

Besides that i have no idea why, no other software is listening on port 25, not postfix nor sendmail.
```

**Comment by jfnz** [comment]
Why do you need to specify such a huge range of ports?

Just use something above port 1024, i.e. a non-privileged port.
