### ISSUE TITLE
loggerOutputFile "not a directory"

### ISSUE THREAD

**Issue by Anderseta** [Storj/storjshare-daemon#150]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.0.0, core: 6.4.3, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

```
To choose a logger file not a logger directory
```

### Actual Behavior

```
loggerOutputFile is expecting a directory now, not a file anymore


 storjshare[2980]: fs.js:640
 storjshare[2980]: return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
 storjshare[2980]: ^
 storjshare[2980]: Error: ENOTDIR: not a directory, open '/var/log/storj.log/c3159334790a311ee8fe0cb477389384959cf6d9_2017-5-30.log'
 storjshare[2980]: at Error (native)
 storjshare[2980]: at Object.fs.openSync (fs.js:640:18)
 storjshare[2980]: at Object.fs.writeFileSync (fs.js:1333:33)
 storjshare[2980]: at FsLogger._newfile (/usr/lib/node_modules/storjshare-daemon/node_modules/fslogger/lib/fslogger.js:84:6)
 storjshare[2980]: at new FsLogger (/usr/lib/node_modules/storjshare-daemon/node_modules/fslogger/lib/fslogger.js:36:10)
 storjshare[2980]: at utils.validateAllocation (/usr/lib/node_modules/storjshare-daemon/lib/api.js:135:24)
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/lib/utils.js:75:14
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:190:13
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:94:25
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:187:17
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:190:13
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:94:25
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:187:17
 storjshare[2980]: at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
```

### Steps to Reproduce

```
1. Download the latest version
2. In config.json put loggerOutputFile as a file, like /var/log/storj.log
3. Start

It works if i instead use /var/log/storj/ for example, but then it creates a log file like this:
 /var/log/storj/c3159334790a311ee8fe0cb477389384959cf6d9_2017-5-30.log
```

**Comment by bookchin** [comment]
Yes, this is a new (backwards incompatible) change - hence the version bump from 2.x.x to 3.x.x. You need to supply a directory now, as the log file will rotate every day.
