### ISSUE TITLE
cannot start node

### ISSUE THREAD

**Issue by katmai** [Storj/storjshare-daemon#152]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.0.0, core: 6.4.3, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

start the node - stay started

### Actual Behavior

after i start the daemon, it throws an error about the log folder not being correct, but it's the same log folder it's been before upgrade too

```
root@storj-343071:~/storjpi# storjshare-daemon -F

  * starting daemon in foreground

{"level":"info","message":"attempting to start share with config at path /root/storj24000","timestamp":"2017-05-31T09:00:24.092Z"}

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: Invalid Log Folder
    at new FsLogger (/usr/lib/node_modules/storjshare-daemon/node_modules/fslogger/lib/fslogger.js:32:3)
    at utils.validateAllocation (/usr/lib/node_modules/storjshare-daemon/lib/api.js:135:24)
    at /usr/lib/node_modules/storjshare-daemon/lib/utils.js:75:14
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:190:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:94:25
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:187:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:190:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:94:25
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:187:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:34:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:190:13
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:94:25
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/node_modules/async/lib/async.js:187:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/du/index.js:21:14

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storjshare-killall
2. storjshare-daemon -F
3. storjshare-load -s ~/.config/shares-shapshot

log folder proof of existence and it's writable
```
root@storj-343071:~/storjpi# cat "/root/storj24000" |grep log
  // Determines how much detail is shown in the log:
  "loggerVerbosity": 3,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid].log
  "loggerOutputFile": "/root/.config/storjshare/logs/9ee85671bf85dd1d006b47431ecdaf167951b313.log",
root@storj-343071:~/storjpi# ls -la /root/.config/storjshare/logs/
total 12
drwxr-xr-x 2 root root 4096 May 31 08:58 .
drwxr-xr-x 5 root root 4096 May 17 12:29 ..
-rw-r--r-- 1 root root  116 May 31 08:59 daemon.log

```

**Comment by AlexeyALeonov** [comment]
You should upgrade storjshare-daemon to 3.1.0

**Comment by katmai** [comment]
npm install -g storjshare-daemon
 does the trick.
