### ISSUE TITLE
Error thrown after node & npm update

### ISSUE THREAD

**Issue by Mistra** [Storj/storjshare-daemon#154]
### Package Versions

**Daemon** daemon: 3.1.0, core: 6.5.0, protocol: 1.1.0
**Node** v8.0.0
**Npm** 4.6.1

### Expected Behavior

**Command** 'storjshare daemon' loads the daemon

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storjshare daemon

  * starting daemon in background
child_process.js:380
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:380:11)
    at Object.exports.spawn (child_process.js:465:38)
    at Function.module.exports.daemon (/usr/lib/node_modules/storjshare-daemon/node_modules/daemon/index.js:50:31)
    at module.exports (/usr/lib/node_modules/storjshare-daemon/node_modules/daemon/index.js:25:20)
    at utils.checkDaemonRpcStatus (/usr/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js:42:7)
    at Socket.<anonymous> (/usr/lib/node_modules/storjshare-daemon/lib/utils.js:158:5)
    at Object.onceWrapper (events.js:312:19)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

### Steps to Reproduce

On archlinux, just updated the system and the distro updated both npm and node to latest, nothing else to report.

**Comment by bookchin** [comment]
We support the LTS release of node, currently 6.10.x.
