### ISSUE TITLE
storjshare daemon crashes when starting on OSX

### ISSUE THREAD

**Issue by lunokhod** [Storj/storjshare-daemon#179]
After installing the latest storjshare deamon with `npm install -g storjshare-daemon` on OSX, the daemon crashes when trying to start it, complaing `throw new TypeError('"cwd" must be a string');`

````
% storjshare -V
daemon: 3.4.0, core: 6.6.0, protocol: 1.1.0
````
Here is the full output
~~~~
% storjshare daemon

  * starting daemon in background
child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at Object.exports.spawn (child_process.js:485:38)
    at Function.module.exports.daemon (/usr/local/lib/node_modules/storjshare-daemon/node_modules/daemon/index.js:50:31)
    at module.exports (/usr/local/lib/node_modules/storjshare-daemon/node_modules/daemon/index.js:25:20)
    at utils.checkDaemonRpcStatus (/usr/local/lib/node_modules/storjshare-daemon/bin/storjshare-daemon.js:53:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/storjshare-daemon/lib/utils.js:212:5)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

~~~~

**Comment by littleskunk** [comment]
Looks like a wrong nodejs version. Please install nodejs lts (v6.11.0 at the moment) and try again.

**Comment by lunokhod** [comment]
confirmed. I was using version 8.
