### ISSUE TITLE
daemon crashes after starting farmer

### ISSUE THREAD

**Issue by cemsbr** [Storj/storjshare-daemon#203]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 3.5.0, core: 6.7.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.11.1 (Note: archlinux nodejs-lts-boron)
```

### Expected Behavior

Normal farming

### Actual Behavior
There's nothing in the logs. Only starting the daemon in foreground shows something.
```
$ storjshare daemon -F  # and start command in another terminal
                                                                               
  * starting daemon in foreground

{"level":"info","message":"attempting to start share with config at path /home/cemsbr/.config/storjshare/config/3bb0db2373aac96501e807778759cf207b75c05e-200.14
5.46.212.json","timestamp":"2017-07-19T18:44:25.180Z"}
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: conf.storageAllocation.match is not a function
    at Object.exports.validateAllocation (/usr/lib/node_modules/storjshare-daemon/lib/utils.js:83:31)
    at RPC.start (/usr/lib/node_modules/storjshare-daemon/lib/api.js:121:11)
    at Proto.apply (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:99:19)
    at Object.dnode.handle (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:140:21)
    at Object.dnode.write (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:106:22)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. storjshare daemon -F
2. storjshare start --config config.json

**Comment by littleskunk** [comment]
Already solved in storjshare-daemon v3.5.1: https://github.com/Storj/storjshare-daemon/commit/749905706f245bbcee38573e5d7d7749bcc42fb1

Close the issue please.
