### ISSUE TITLE
"storjshare-status --json" does not print JSON

### ISSUE THREAD

**Issue by buckley310** [Storj/storjshare-daemon#213]
### Package Versions

Replace the values below using the output from `storjshare --version`.
```
daemon: 3.5.1, core: 6.7.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.
```
v6.11.1
```

### Expected Behavior
`storjshare-status --json` outputs JSON

### Actual Behavior
`storjshare-status --json` outputs a pretty-printed object, not a JSON-serialized object
https://github.com/Storj/storjshare-daemon/blob/v3.5.1/bin/storjshare-status.js#L102

### Steps to Reproduce
Small test case for Linux:
```
$ node -e 'require("child_process").exec("storjshare-status -j",(x,stdout,y)=>JSON.parse(stdout))'                                               
undefined:1
[ { id: '[omitted]',
    ^

SyntaxError: Unexpected token i in JSON at position 4
    at Object.parse (native)
    at require.exec ([eval]:1:73)
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
$ 
```

**Comment by littleskunk** [comment]
Please add the json output.

**Comment by buckley310** [comment]
This is stock behavior.
```
$ storjshare-status -j
[ { id: '[omitted]',
    status: 'running',
    configPath: '/srv/storj/int/int',
    uptime: '5d 10h 24m 18s',
    restarts: 0,
    peers: 166,
    offers: 77357,
    dataReceivedCount: 890,
    delta: '10ms',
    port: 5000,
    shared: '1.89GB',
    sharedPercent: '1' } ]
$
```

I have patched my local copy by adding `JSON.stringify()` to [line 94](https://github.com/Storj/storjshare-daemon/blob/v3.5.1/bin/storjshare-status.js#L94), which results in the following.
```
$ storjshare-status -j
[{"id":"[omitted]","status":"running","configPath":"/srv/storj/int/int","uptime":"5d 10h 25m 34s","restarts":0,"peers":161,"offers":77359,"dataReceivedCount":890,"delta":"10ms","port":5000,"shared":"1.89GB","sharedPercent":"1"}]
$
```

**Comment by Techwolf12** [comment]
As the pull request is merged, the issue should be closed right? ;)
