### ISSUE TITLE
Deamon hung up if i want to start a node

### ISSUE THREAD

**Issue by yanilie** [Storj/storjshare-daemon#22]
storjshare --version
2.0.4
```
node --version
v6.9.4


### Actual Behavior

Deamon hung up if i want to start a node

```

```

### Steps to Reproduce

1. storjshare daemon --foreground

{"level":"info","message":"attempting to start share with config at path /storj/config.json","timestamp":"2017-01-14T00:18:43.936Z"}
stream.js:74
throw er; // Unhandled stream error in pipe.
^

Error: Non-base58 character
at Object.decode (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/node_modules/bs58/lib/bs58.js:51:37)
at Function.Base58.decode (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/encoding/base58.js:48:26)
at Function.Base58Check.decode (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/encoding/base58check.js:45:31)
at Function.PrivateKey._transformWIF (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/privatekey.js:196:50)
at PrivateKey._classifyArguments (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/privatekey.js:108:25)
at new PrivateKey (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/privatekey.js:48:19)
at Function.PrivateKey.fromString.PrivateKey.fromWIF (/usr/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/privatekey.js:236:10)
at new KeyPair (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/crypto-tools/keypair.js:22:40)
at Object.KeyPair (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/crypto-tools/keypair.js:18:12)
at RPC.start (/usr/lib/node_modules/storjshare-daemon/lib/api.js:88:24)
at Proto.apply (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:123:13)
at Proto.handle (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:99:19)
at Object.dnode.handle (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:140:21)
at Object.dnode.write (/usr/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:106:22)
at Socket.ondata (_stream_readable.js:555:20)
at emitOne (events.js:96:13)

2. storjshare start --config /storj/config.json

(Debian, Vserver)

**Comment by littleskunk** [comment]
Looks like a bad payout address or something like that. Please send my your config file as PM on slack. It contains a private key so don't upload it in a public chat or on github.

**Comment by yanilie** [comment]
Hi, thank you! The Problem was a wrong --key , fixed now and works!
