### ISSUE TITLE
Unhandled exception - Nano not installed

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-daemon#23]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.4
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

Please describe the program's expected behavior.

My prefered editor is vi and not nano. I would expect to open the config file in vi or at least don't print out the exeception.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
root@storj:~# storjshare create --sjcx ...

  * configuration written to /opt/tmp/636ac391e41f6965381d17b4b22d96b5dc36c470.json
  * opening in your favorite editor to tweak before running
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by bookchin** [comment]
If you set $EDITOR it will use that.

**Comment by bookchin** [comment]
I'll add some better detection of which editor is installed
