### ISSUE TITLE
syntax error: Unexpected token

### ISSUE THREAD

**Issue by neerbeer** [Storj/storjshare-daemon#243]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
storjshare --version
/usr/local/lib/node_modules/storjshare-daemon/bin/storjshare.js:6
const {version, bin} = require('../package');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

Replace the values below using the output from `node --version`.

```
v4.2.6
```

### Expected Behavior

The program should output the version number

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 storjshare --version
/usr/local/lib/node_modules/storjshare-daemon/bin/storjshare.js:6
const {version, bin} = require('../package');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. followed the cli install guide
2. apt update && apt install build-essential -y 
3. ...

storjshare start
/usr/local/lib/node_modules/storjshare-daemon/bin/storjshare.js:6
const {version, bin} = require('../package');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

$ nvm --version
0.33.0

$ node --version
v4.2.6

$ npm --version
3.5.2

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

$ storjshare --version
/usr/local/lib/node_modules/storjshare-daemon/bin/storjshare.js:6
const {version, bin} = require('../package');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by neerbeer** [comment]
Tried the instructions again, apt upgrade && reboot and things started working
