### ISSUE TITLE
Node stopped - if (contact.hdKey) { ^ TypeError: Cannot read property

### ISSUE THREAD

**Issue by vzol24** [Storj/storjshare-daemon#258]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.0.1, core: 8.0.0, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.3
```

### Expected Behavior

The node does not stop.

### Actual Behavior

Node status: stopped.

```
/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/item.js:81
  if (contact.hdKey) {
             ^

TypeError: Cannot read property 'hdKey' of undefined
    at StorageItem.getContract (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/item.js:81:14)
    at /home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:273:29
    at /home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/manager.js:64:5
    at /home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapter.js:64:5
    at /home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:89:11
    at _getSbucketForKey (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:355:7)
    at Btable._getSbucketForKey (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:162:5)
    at Btable.createWriteStream (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:350:10)
    at _getShardStreamPointer (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:82:9)
    at /home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:93:7
    at _db.get (/home/zzzzz/.nvm/versions/node/v6.11.3/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/s-bucket.js:222:7)
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2017-09-24T20:16:48.686Z"}


```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by dantidote** [comment]
I'm getting the same error, and when it happens, my node restarts.

`daemon: 5.1.0, core: 8.1.0, protocol: 1.2.0`

**Comment by felixbrucker** [comment]
Got the same on one of my nodes:

`daemon: 5.1.0, core: 8.2.0, protocol: 1.2.0`

**Comment by Jurisg** [comment]
Got same crash on one node too today.
2 times node restarted 3 time crashed.
 
`daemon: 5.1.0, core: 8.3.0, protocol: 1.2.0`
```/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/item.js:81
  if (contact.hdKey) {
             ^

TypeError: Cannot read property 'hdKey' of undefined
    at StorageItem.getContract (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/item.js:81:14)
    at /home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:277:29
    at /home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/manager.js:64:5
    at /home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapter.js:64:5
    at /home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:89:11
    at _getSbucketForKey (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:355:7)
    at Btable._getSbucketForKey (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:162:5)
    at Btable.createWriteStream (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:350:10)
    at _getShardStreamPointer (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:82:9)
    at /home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:93:7
    at _db.get (/home/node/.nvm/versions/node/v6.11.4/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/s-bucket.js:222:7)```

**Comment by LuckyFellow** [comment]
Got the same crash

> daemon: 5.1.0, core: 8.2.1, protocol: 1.2.0

Node restarts and crashes right after again.
I find the same log message in my logfile as posted before.
I don't know how to reproduce the crash.
It happened while I wasn't logged into the server.

**Comment by gbaker3** [comment]
I also see the same bug. Restarted twice last night after over 6 months with no restarts. Windows 10 Pro 64-bit, build 15063.608.

`gui 7.1.0 daemon: 5.1.0, core: 8.2.0, protocol: 1.2.0`

```
C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\item.js:81
  if (contact.hdKey) {
             ^

TypeError: Cannot read property 'hdKey' of undefined
    at StorageItem.getContract (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\item.js:81:14)
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\shard-server.js:275:29
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\manager.js:64:5
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapter.js:64:5
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:89:11
    at _getSbucketForKey (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:355:7)
    at Btable._getSbucketForKey (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:162:5)
    at Btable.createWriteStream (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:350:10)
    at _getShardStreamPointer (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:82:9)
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:93:7
    at _db.get (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\s-bucket.js:222:7)
C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\item.js:81
  if (contact.hdKey) {
             ^

TypeError: Cannot read property 'hdKey' of undefined
    at StorageItem.getContract (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\item.js:81:14)
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\shard-server.js:275:29
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\manager.js:64:5
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapter.js:64:5
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:89:11
    at _getSbucketForKey (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:355:7)
    at Btable._getSbucketForKey (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:162:5)
    at Btable.createWriteStream (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:350:10)
    at _getShardStreamPointer (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:82:9)
    at C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:93:7
    at _db.get (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\s-bucket.js:222:7)
```

**Comment by geomna** [comment]
Got the same crash:
daemon: 5.1.0, core: 8.2.0, protocol: 1.2.0
v6.11.2
Exactly the same as @LuckyFellow tells
After 2 restarts, the node again works fine...

**Comment by gsxryan** [comment]
Same crash here

Daemon 5.1.0 Core 8.1.0 Protocol 1.2.0 GUI 7.1.0, Windows 10 x64 Reproduced during Sept & Oct Patches.

I've had this crash since SIP6 was turned on.  It was very bad initially, multiple times per day.  Now i get one every day or so.  This is likely only due to the network slowing down.  I wasn't able to catch one node fast enough and it shut down, bumping my responsetime from 250ms to 9000ms.  Resource utilization does not bottleneck.

**Comment by guelz** [comment]
Same here...
Daemon 5.1.0 Core 8.1.0 Protocol 1.2.0 GUI 7.1.0, Windows 10 x64
13 restarts in 14 days.

**Comment by juergschwarz** [comment]
Same here on Ubuntu 16.04 LTS
daemon: 5.1.0, core: 8.3.0, protocol: 1.2.0

$ free
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:     8058900     1987436      191044       54560     5880420     5642548
Auslagerungsspeicher:     8269820     3692332     4577488

**Comment by gsxryan** [comment]
I started a new node (#2).  It's now been up longer than my old nodes without a restart.

![image](https://user-images.githubusercontent.com/2055136/31593588-2d3b6d12-b1f5-11e7-8926-2c64ee6bd672.png)

**Comment by littleskunk** [comment]
Please upload a complete logfile. I have an idea what the reason could be.

**Comment by gbaker3** [comment]
> Please upload a complete logfile. I have an idea what the reason could be.

See attached log file from yesterday. Error occurs 4 times from what I can tell. Hopefully log verbosity level 3 is good enough for what you need.

[d017e8e7749be8c4577d669f972ee4f599737c11_2017-10-16.log](https://github.com/Storj/storjshare-daemon/files/1392240/d017e8e7749be8c4577d669f972ee4f599737c11_2017-10-16.log)

**Comment by littleskunk** [comment]
Return statement is missing: https://github.com/Storj/core/blob/b8123cb6bd164613c6a8421ed9ba4cd32c053e28/lib/network/shard-server.js#L261

I will work on a pull request.

**Comment by Pandemik** [comment]
I'm getting restarts... 
daemon: 5.1.0, core: 8.3.0, protocol: 1.2.0

**Comment by littleskunk** [comment]
core version v8.3.1 ...
