### ISSUE TITLE
storjshare-create cannot find module './build/Release/diskusage.node'

### ISSUE THREAD

**Issue by nathanowen42** [Storj/storjshare-daemon#280]
### Package Versions

`storjshare --version`.
```
daemon: 5.1.0, core: 8.3.0, protocol: 1.2.
```

`node --version`.
```
v6.11.4
```

### Expected Behavior

storjshare-create should create the specified node

### Actual Behavior

storjshare-create fails with the following error

```
module.js:529
    throw err;
    ^

Error: Cannot find module './build/Release/diskusage.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/node_modules/diskusage/index.js:1:76)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

### Steps to Reproduce

1. Install fresh copy of Fedora 27
2. Perform install in accordance with instructions on the Storj/storjshare-daemon github page.
3. Run this command:
````
sudo storjshare-create --storj 0x1e4542AF5EB35eC0F0744Ed1D828a8Bdd66e1844 --storage /hdd1 --size 7180000MB --outfile /storjshare/hdd1/config.json --rpcaddress myddnsaddress.ddns.net --rpcport 4000 --manualforwarding true --logdir /storjshare/hdd1/logs
````

**Comment by nathanowen42** [comment]
Seems to work if run as a normal user instead of as root.  This will make setup somewhat more difficult.  Will update status soon.

**Comment by nathanowen42** [comment]
Okay, I have found the issue.  nvm is only installed for a single user.  I will work out how to install globally and setup an appropriate selinux policy module for nvm.  I will update this once done.

**Comment by nathanowen42** [comment]
...That is if I don't give up and re-write the whole thing in C out of pure masochism.

**Comment by braydonf** [comment]
This is pretty common issue with installing via npm as root, as it will exec as user `nobody`

**Comment by AlexeyALeonov** [comment]
Don't use the root, it's doesn't safe

**Comment by sunk818** [comment]
Maybe there can be specific instructions for Google Cloud? I'm trying the free tier and `npm install -g` does not want to install without using `sudo`

**Comment by freeelectron-ro** [comment]
I installed three times following every single step. NOT working at all. Please provide a clear workaround for this issue.

this is the message:
storjshare -h
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './build/Release/diskusage.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/storjshare-daemon/node_modules/diskusage/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by AlexeyALeonov** [comment]
Don't use the root. Please, remove the node.js via package manager and follow this guide: https://docs.storj.io/docs/storj-share-daemon-cli#section-2-1-1-installation-of-the-required-components

If you still want to use a root, then try to install the diskuage package

`sudo npm install -g diskusage`
