### ISSUE TITLE
restart with an error

### ISSUE THREAD

**Issue by strahe** [storj/storjshare-daemon#285]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v6.11.4
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

```
{"level":"debug","message":"contract is associated with connected bridge: true","timestamp":"2017-10-26T07:52:20.627Z"}
{"level":"debug","message":"active transfers 0 is less than offerBackoffLimit 10: true","timestamp":"2017-10-26T07:52:20.628Z"}
{"level":"debug","message":"no storage item available for this shard","timestamp":"2017-10-26T07:52:20.630Z"}
{"level":"debug","message":"negotiator returned: true","timestamp":"2017-10-26T07:52:20.630Z"}
{"level":"debug","message":"max KFS bucket size 7086696038, used 0, free 7086696038, shard size 101","timestamp":"2017-10-26T07:52:20.804Z"}
{"level":"debug","message":"we have enough free space: true","timestamp":"2017-10-26T07:52:20.805Z"}
/usr/lib/node_modules/storjshare-daemon/node_modules/_bitcore-lib@0.13.19@bitcore-lib/lib/crypto/signature.js:158
  var b2 = this.r.toBuffer({
                  ^

TypeError: this.r.toBuffer is not a function
    at Signature.toCompact (/usr/lib/node_modules/storjshare-daemon/node_modules/_bitcore-lib@0.13.19@bitcore-lib/lib/crypto/signature.js:158:19)
    at Message.sign (/usr/lib/node_modules/storjshare-daemon/node_modules/_bitcore-message@1.0.4@bitcore-message/lib/message.js:63:20)
    at Contract.signExternal (/usr/lib/node_modules/storjshare-daemon/node_modules/_storj-lib@8.4.2@storj-lib/lib/contract/index.js:262:18)
    at Contract.sign (/usr/lib/node_modules/storjshare-daemon/node_modules/_storj-lib@8.4.2@storj-lib/lib/contract/index.js:239:46)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/_storj-lib@8.4.2@storj-lib/lib/network/farmer.js:787:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/_storj-lib@8.4.2@storj-lib/lib/network/farmer.js:684:9
    at handleStatResults (/usr/lib/node_modules/storjshare-daemon/node_modules/_storj-lib@8.4.2@storj-lib/lib/storage/adapters/embedded.js:217:9)
    at _getStat (/usr/lib/node_modules/storjshare-daemon/node_modules/_kfs@4.0.0@kfs/lib/b-table.js:186:9)
    at sBucket.stat (/usr/lib/node_modules/storjshare-daemon/node_modules/_kfs@4.0.0@kfs/lib/b-table.js:208:11)
    at _db.approximateSize (/usr/lib/node_modules/storjshare-daemon/node_modules/_kfs@4.0.0@kfs/lib/s-bucket.js:400:7)

```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
