### ISSUE TITLE
Storjshare stops when trying to send HTTP headers to clients on network

### ISSUE THREAD

**Issue by madcatsu** [Storj/storjshare-daemon#293]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v7.10.1
```

### Expected Behavior

`storjshare status` should show node is running.

### Actual Behavior

Storjshare stops with error that HTTP headers have already been sent when replying to message from another client.

```
{"level":"info","message":"replying to message to 3c0d06ff2a88ffa43b86b812b239e5c10b8aec4d","timestamp":"2017-11-12T10:10:36.616Z"}
_http_outgoing.js:371
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.format (/usr/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:147:10)
    at ServerResponse.send (/usr/lib/node_modules/storjshare-daemon/node_modules/restify/lib/response.js:340:14)
    at Transport._send (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/transport.js:261:45)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:187:12
    at Transport.RPC._trigger (/usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:297:12)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:173:10
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:309:5
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:251:17
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:154:25
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:612:34
    at FarmerInterface.Network._signMessage (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:540:3)
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:146:13)
```

### Steps to Reproduce

`storjshare status` shows status as stopped after running for a number of days. Storjshare daemon is still running as referenced by output of `storjshare daemon --status` showing daemon is running. `storjshare start` is executed on the farming node and the node comes online until the error occurs again.

**Comment by littleskunk** [comment]
Nodejs 7 is not supported.

Close it please.

**Comment by madcatsu** [comment]
Updated and confirmed issue resolved.
