### ISSUE TITLE
Problem at installation with debian 8.9

### ISSUE THREAD

**Issue by buxx** [Storj/storjshare-daemon#298]
### Package Versions

`node --version`:

```
v8.9.1
```

### Expected Behavior

Command `npm install --global storjshare-daemon` should install storjshare-daemon.

### Actual Behavior

When execute command `npm install --global storjshare-daemon`, an eror is produced:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git
npm ERR! 
npm ERR! fatal: failed to stat '.': Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-23T10_00_15_730Z-debug.log
```

Content of `/root/.npm/_logs/2017-11-23T10_00_15_730Z-debug.log` is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'storjshare-daemon' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 92f25d33fb6fc0ee
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/storjshare-daemon 247ms (from cache)
8 silly pacote tag manifest for storjshare-daemon@latest fetched in 290ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule storjshare-daemon@5.2.0 checking installable status
14 silly fetchPackageMetaData error for daemon@github:zipang/daemon.node#48d0977c26fb3a6a44ae99aae3471b9d5a761085 Error while executing:
14 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git
14 silly fetchPackageMetaData
14 silly fetchPackageMetaData fatal: failed to stat '.': Permission denied
14 silly fetchPackageMetaData
14 silly fetchPackageMetaData exited with error code: 128
15 http fetch GET 200 https://registry.npmjs.org/async 97ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/colors 94ms (from cache)
17 http fetch GET 200 https://registry.npmjs.org/commander 95ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/editor 85ms (from cache)
19 silly pacote range manifest for async@^2.5.0 fetched in 111ms
20 silly resolveWithNewModule async@2.6.0 checking installable status
21 silly pacote range manifest for colors@^1.1.2 fetched in 106ms
22 silly resolveWithNewModule colors@1.1.2 checking installable status
23 silly pacote range manifest for commander@^2.11.0 fetched in 109ms
24 silly resolveWithNewModule commander@2.12.0 checking installable status
25 silly pacote range manifest for editor@^1.0.0 fetched in 104ms
26 silly resolveWithNewModule editor@1.0.0 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/blindfold 221ms (from cache)
28 silly pacote version manifest for blindfold@0.0.1 fetched in 228ms
29 silly resolveWithNewModule blindfold@0.0.1 checking installable status
30 http fetch GET 304 https://registry.npmjs.org/bytes 233ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/cli-table 233ms (from cache)
32 http fetch GET 304 https://registry.npmjs.org/du 227ms (from cache)
33 silly pacote range manifest for bytes@^3.0.0 fetched in 241ms
34 silly resolveWithNewModule bytes@3.0.0 checking installable status
35 silly pacote range manifest for cli-table@^0.3.1 fetched in 242ms
36 silly resolveWithNewModule cli-table@0.3.1 checking installable status
37 http fetch GET 200 https://registry.npmjs.org/rc 17ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/diskusage 198ms (from cache)
39 silly pacote range manifest for du@^0.1.0 fetched in 236ms
40 silly resolveWithNewModule du@0.1.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/mkdirp 136ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/fslogger 148ms (from cache)
43 silly pacote range manifest for rc@^1.2.2 fetched in 31ms
44 silly resolveWithNewModule rc@1.2.2 checking installable status
45 silly pacote range manifest for diskusage@^0.2.4 fetched in 213ms
46 silly resolveWithNewModule diskusage@0.2.4 checking installable status
47 silly pacote range manifest for mkdirp@^0.5.1 fetched in 151ms
48 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
49 silly pacote range manifest for fslogger@^2.0.2 fetched in 162ms
50 silly resolveWithNewModule fslogger@2.0.2 checking installable status
51 http fetch GET 304 https://registry.npmjs.org/kad-logger-json 161ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/dnode 269ms (from cache)
53 http fetch GET 200 https://registry.npmjs.org/strip-json-comments 32ms (from cache)
54 silly pacote range manifest for kad-logger-json@^0.1.2 fetched in 177ms
55 silly resolveWithNewModule kad-logger-json@0.1.2 checking installable status
56 http fetch GET 200 https://registry.npmjs.org/tail 29ms (from cache)
57 silly pacote range manifest for dnode@^1.2.2 fetched in 281ms
58 silly resolveWithNewModule dnode@1.2.2 checking installable status
59 silly pacote range manifest for strip-json-comments@^2.0.1 fetched in 44ms
60 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
61 http fetch GET 304 https://registry.npmjs.org/pretty-ms 177ms (from cache)
62 silly pacote range manifest for tail@^1.2.3 fetched in 38ms
63 silly resolveWithNewModule tail@1.2.3 checking installable status
64 silly pacote range manifest for pretty-ms@^3.0.1 fetched in 184ms
65 silly resolveWithNewModule pretty-ms@3.1.0 checking installable status
66 http fetch GET 304 https://registry.npmjs.org/readable-stream 69ms (from cache)
67 silly pacote range manifest for readable-stream@^2.3.3 fetched in 73ms
68 silly resolveWithNewModule readable-stream@2.3.3 checking installable status
69 http fetch GET 304 https://registry.npmjs.org/touch 54ms (from cache)
70 silly pacote version manifest for touch@3.1.0 fetched in 58ms
71 silly resolveWithNewModule touch@3.1.0 checking installable status
72 http fetch GET 304 https://registry.npmjs.org/storj-lib 79ms (from cache)
73 silly pacote range manifest for storj-lib@^8.4.2 fetched in 88ms
74 silly resolveWithNewModule storj-lib@8.4.2 checking installable status
75 http fetch GET 304 https://registry.npmjs.org/web3-utils 71ms (from cache)
76 silly pacote range manifest for web3-utils@^1.0.0-beta fetched in 73ms
77 silly resolveWithNewModule web3-utils@1.0.0-beta.26 checking installable status
78 verbose stack Error: exited with error code: 128
78 verbose stack     at ChildProcess.onexit (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
78 verbose stack     at emitTwo (events.js:126:13)
78 verbose stack     at ChildProcess.emit (events.js:214:7)
78 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
79 verbose cwd /root
80 verbose Linux 3.14.32-xxxx-grs-ipv6-64
81 verbose argv "/root/.nvm/versions/node/v8.9.1/bin/node" "/root/.nvm/versions/node/v8.9.1/bin/npm" "install" "--global" "storjshare-daemon"
82 verbose node v8.9.1
83 verbose npm  v5.5.1
84 error Error while executing:
84 error /usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git
84 error
84 error fatal: failed to stat '.': Permission denied
84 error
84 error exited with error code: 128
85 verbose exit [ 1, true ]
```

### Steps to Reproduce

On debian 8.9, as root in /root folder:

1. `wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash`
2. `nvm install --lts`
3. `apt install git python build-essential`
4. `npm install --global storjshare-daemon`

**Comment by buxx** [comment]
Maybe can help, if i execute `/usr/bin/git ls-remote -h -t ssh://git@github.com/zipang/daemon.node.git`, as root, in /root:

```
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by buxx** [comment]
If run command `npm install storjshare-daemon` **without** `--global` option and with non-root user, install succeed.

**Comment by littleskunk** [comment]
Installing storjshare as root is not a good idea. Better create a new user for storjshare.

If you are sure you want to install it as root you can add --unsafe-perm.

Issue can be closed.

**Comment by buxx** [comment]
Okay. The error result using root user ? If yes, it must be indicated in the readme file. If it's not, maybe it can be mention of "better idea to use non root-user".

I can make the pull request if you are ok.

Thank's for resolution.

**Comment by littleskunk** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by buxx** [comment]
Ok ^^
