### ISSUE TITLE
Install Issues for FreeBSD 11 [Error Displayed Before Every Command]

### ISSUE THREAD

**Issue by ajm113** [Storj/storjshare-daemon#299]
### Package Versions

Storjshare Ver:
```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

Node and NPM version

```
Node: v9.1.0
npm: 4.6.1
```
FreeBSD Machine:
```
FreeBSD STORJ 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 04:10:47 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386
```

I should also note I'm running node/storjshare inside a jail.

### Expected Behavior

Not seeing an error before every command?

### Actual Behavior

Displays this error before every command.

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/storjshare-daemon/node_modules/dtrace-provider/dtrace-provider.js:18:23)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3) code: 'MODULE_NOT_FOUND' }
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `cd /usr/ports/www/npm4 && make install clean`
2. Continue with all default settings on display.
3. `npm i -g storjshare-daemon --unsafe-perm`
4. `storjshare`

P.S I have attempted to use pkg to install node/npm, but then it seems like storjshare wont start at all due to missing module that handles the drive information. Using ports is the closes working thing I got thus far.

**Comment by littleskunk** [comment]
wrong nodejs version.

**Comment by ajm113** [comment]
My mistake, any plans of support for newer releases of node?

**Comment by littleskunk** [comment]
Yes sure but we are supporting the LTS line. We are supporting any new LTS version.
