### ISSUE TITLE
Fun Windows Issues

### ISSUE THREAD

**Issue by super3** [Storj/storjshare-daemon#3]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
2.0.0
```

Replace the values below using the output from `node --version`.

```
v6.9.4
```

### Expected Behavior

Run start running the daemon. 

### Actual Behavior

Try to run the generated config results in an error.

```
C:\Users\work>storjshare start --config "C:\Users\work\AppData\Local\Temp\8a84785601268ae7501c788457549098e98aef42.json"
undefined:56
  "loggerOutputFile": "C:\Users\work\.config\storjshare\logs\8a84785601268ae7501c788457549098e98aef42.log",
                          ^

SyntaxError: Unexpected token U in JSON at position 727
    at Object.parse (native)
    at exports.parse (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\lib\utils.js:15:17)
    at addConfigFile (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\index.js:31:20)
    at module.exports (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\index.js:47:20)
    at Object.<anonymous> (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\lib\config\daemon.js:16:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

So if you add backslashes to the path you still get: 

```
C:\Users\work>storjshare start --config "C:\Users\work\AppData\Local\Temp\8a84785601268ae7501c788457549098e98aef42.json"
undefined:58
  "storagePath": "D:\",


SyntaxError: Unexpected token
 in JSON at position 841
    at Object.parse (native)
    at exports.parse (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\lib\utils.js:15:17)
    at addConfigFile (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\index.js:31:20)
    at module.exports (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\node_modules\rc\index.js:47:20)
    at Object.<anonymous> (C:\Users\work\AppData\Roaming\nvm\v6.9.2\node_modules\storjshare-daemon\lib\config\daemon.js:16:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

After you add the backslashes for the storage path too:
```
C:\Users\work>storjshare start --config "C:\Users\work\AppData\Local\Temp\8a84785601268ae7501c788457549098e98aef42.json"

  failed to start share, reason: failed to read config at C:\Users\work\C:\Users\work\AppData\Local\Temp\8a84785601268ae7501c788457549098e98aef42.json
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Generate the config.
2. Try to run the generated config. 
3. Add double blackslashes to loggerOutputFile
4. Add double blackslashes to storagepath
5. Looks for config in the wrong place.

**Comment by MeijeSibbel** [comment]
C:\Users\Meije>storjshare create -k f3f5c4368b4db87edd2aa43080f37f90b2813634dd6caea24ae0c1deeab6afa9 -a 1PxLPVqmYxM592U3KNAK6EUyhizBpXhA96 -s E:\StorjCLI -o E:\StorjCLI

  * daemon is not running, starting...

  failed to write config, reason: ENOENT: no such file or directory, open 'C:\Users\Meije\E:\StorjCLI'

C:\Users\Meije>

**Comment by MeijeSibbel** [comment]
```
C:\Users\Meije>storjshare start --config storjshare/config.json
undefined:56
  "loggerOutputFile": "C:\Users\Meije\.config\storjshare\logs\72d6daaa086a7e25d53c58234d03bf9594b78590.log",
                          ^

SyntaxError: Unexpected token U in JSON at position 732
    at Object.parse (native)
    at exports.parse (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\lib\utils.js:15:17)
    at addConfigFile (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\index.js:31:20)
    at module.exports (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\rc\index.js:47:20)
    at Object.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\lib\config\daemon.js:16:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

C:\Users\Meije>

```
