### ISSUE TITLE
storjshare start: failed to start share, reason: invalid directory

### ISSUE THREAD

**Issue by ZigzagoonBalloon** [Storj/storjshare-daemon#301]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
```

Replace the values below using the output from `node --version`.

```
v8.9.1
```

### Expected Behavior

For storj node to start.

### Actual Behavior

Please describe the program's actual behaviour. Please include any stack traces
or log output in the back ticks below.

```
I get the error in the title. failed to start share, reason: invalid directory.
Run the command: storjshare start --config /home/pi/.config/storjshare/configs/abe762xxxx06d5b8.json
Config file exists and can be viewed and edited. Following the pi tutorial here: https://docs.storj.io/v1.1/docs/setting-up-storj-share-on-a-raspberry-pi.

I have seen this issue https://github.com/Storj/storjshare-daemon/issues/122 but that seems related to using snap which I did not use.

**Logs:**
AssertionError [ERR_ASSERTION]: Invalid directory path supplied
    at EmbeddedStorageAdapter._validatePath (/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:50:3)
    at new EmbeddedStorageAdapter (/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:25:8)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/storjshare-daemon/script/farmer.js:37:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
assert.js:42
  throw new errors.AssertionError({

**Config:**
  // doNotTraverseNat: false Enables NAT traversal strategies
  // first UPnP, then reverse HTTP tunnel
  // if that fails. Disable if you are public or using dynamic DNS
  "doNotTraverseNat": false,
  // Maximum number of tunnels to provide to the network
  // Tunnels help nodes with restrictive network configurations participate
  "maxTunnels": 3,
  // Maximum number of concurrent connections to allow
  "maxConnections": 150,
  // If providing tunnels, the starting and ending port range to open for
  // them
  "tunnelGatewayRange": {
    "min": 4001,
    "max": 4003
  },
  // Number of times to retry joining the network and the wait time between
  "joinRetry": {
    "times": 3,
    "interval": 5000
  },
  // Temporarily stop sending OFFER messages if more than this number of shard
  // transfers are active
  "offerBackoffLimit": 4,
  // ECDSA private key for your network identity, your Node ID is derived from
  // this and it is used to sign and verify messages
  "networkPrivateKey": "censored",
  // Determines how much detail is shown in the log:
  // 4 - DEBUG | 3 - INFO | 2 - WARN | 1 - ERROR | 0 - SILENT
  "loggerVerbosity": 3,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid]_date.log
  "loggerOutputFile": "/home/pi/.config/storjshare/logs",
  // Directory path to store contracts and shards
  "storagePath": "/mnt/storj1/storj.io",
  // Amount of space to lease to the network, as human readable string
  // Valid units are B, KB, MB, GB, TB
  "storageAllocation": "7GB"
  // Max size of shards that will be accepted and stored
  // Use this and make this lower if you don't have a strong internet connection
  // "maxShardSize": "100MB"
}

```

**Comment by stefanbenten** [comment]
Hi, your node version is not supported right now! Make sure to install the LTS Version which should be 6.X!

**Comment by littleskunk** [comment]
v8.9.1 is the current LTS version ;)

One folder is missing. `/home/pi/.config/storjshare/logs` or `/mnt/storj1/storj.io`

**Comment by ZigzagoonBalloon** [comment]
Fixed by creating the /mnt/storj1/storj.io directory. Assumed, wrongly, it would make it automatically. Thanks all.
