### ISSUE TITLE
Error in bindings.js

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-daemon#310]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
v5.3.0
```

Replace the values below using the output from `node --version`.

```
v8.9.3
```

### Expected Behavior

Work normally.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
storjshare status
/usr/lib/node_modules/storjshare-daemon/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/build/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/build/Release/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/Debug/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/out/Release/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/Release/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/build/default/leveldown.node
 → /usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/compiled/8.9.3/linux/x64/leveldown.node
    at bindings (/usr/lib/node_modules/storjshare-daemon/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/shard-server.js:8:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install via sudo snap install storjshare

**Comment by littleskunk** [comment]
Remove the failed storjshare-daemon installation first
`rm -rf /usr/lib/node_modules/storjshare-daemon`

Install the snap package again and it should work.
