### ISSUE TITLE
Error: Cannot find module './build/Release/diskusage.node'

### ISSUE THREAD

**Issue by backlight001** [Storj/storjshare-daemon#322]
Error: Cannot find module './build/Release/diskusage.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.9.4/lib/node_modules/storjshare-daemon/node_modules/diskusage/index.js:1:76)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by littleskunk** [comment]
Realy? Next time please use the issue template. A lot of important informations are missing. Last but not least take a look at the open issue befor posting a duplicate issue. #318
