### ISSUE TITLE
TypeError: rpc.save is not a function

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-daemon#33]
### Package Versions

OS: windows 10

Replace the values below using the output from `storjshare --version`.

```
2.1.0
```

Replace the values below using the output from `node --version`.

```
6.9.4
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\Users\Meije>storjshare save
C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\bin\storjshare-save.js:31
  rpc.save(storjshare_save.snapshot, (err) => {
      ^

TypeError: rpc.save is not a function
    at D.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\bin\storjshare-save.js:31:7)
    at emitTwo (events.js:106:13)
    at D.emit (events.js:191:7)
    at Proto.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode\lib\dnode.js:53:14)
    at emitOne (events.js:96:13)
    at Proto.emit (events.js:188:7)
    at Proto.handleMethods (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode-protocol\index.js:118:10)
    at Proto.handle (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode-protocol\index.js:77:14)
    at D.dnode.handle (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode\lib\dnode.js:140:21)
    at D.dnode.write (C:\Users\Meije\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\dnode\lib\dnode.js:106:22)

C:\Users\Meije>

After this error it killed my running node. It worked the second time though after restarting the node again, so this was a one-time error so far. The node was running non-stop for 4 days. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `Storjshare save`
2. Error
3. ...

**Comment by bookchin** [comment]
Ah, this is because when upgrading you must restart the daemon with `storjshare killall`. The CLI bundled was expecting support for that RPC method, but the daemon had not restarted from the previous version.
