### ISSUE TITLE
Error while using storjshare save command (OSX)

### ISSUE THREAD

**Issue by babonet13** [Storj/storjshare-daemon#34]
OS = OSX (Sierra)
storjshare --version => deamon : 2.1.0, core : 6.0.12, protocol : 1.0.0

MacMini-de-Admin:DataFarming Administrateur$ storjshare save --snapshot /Users/Administrateur/DataFarming/conf.txt
/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/bin/storjshare-save.js:31
rpc.save(storjshare_save.snapshot, (err) => {
^

TypeError: rpc.save is not a function
at D.<anonymous> (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/bin/storjshare-save.js:31:7)
at emitTwo (events.js:106:13)
at D.emit (events.js:191:7)
at Proto.<anonymous> (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:53:14)
at emitOne (events.js:96:13)
at Proto.emit (events.js:188:7)
at Proto.handleMethods (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:118:10)
at Proto.handle (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:77:14)
at D.dnode.handle (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:140:21)
at D.dnode.write (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:106:22)

**Comment by bookchin** [comment]
duplicate https://github.com/Storj/storjshare-daemon/issues/33
