### ISSUE TITLE
storjshare crashing when trying to create a share

### ISSUE THREAD

**Issue by MaxMatti** [storj/storjshare-daemon#340]
### Package Versions

```
$ storjshare --version
daemon: 5.3.1, core: 8.7.2, protocol: 1.2.0
$ which vi
/usr/bin/vi
$ which nano
/bin/nano
$ echo "$VISUAL;$EDITOR"
nano;nano
```

Installed with snap on Ubuntu 18.04, so node is not installed.

### Expected Behavior

When running the command `storjshare create --storj 0xC83523983f60955D70720E839cdFc66D8eF1e64A --storage /home/max/gdrive/storj1 --size 10TB` I should create a new share.

### Actual Behavior

```
$ storjshare create --storj 0xC83523983f60955D70720E839cdFc66D8eF1e64A --storage /home/max/storj1 --size 1TB

  * configuration written to /home/max/snap/storjshare/36/.config/storjshare/configs/c4682fd1463a82e89adcd7c8b9256828d21a1cbd.json
  * opening in your favorite editor to tweak before running
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at module.exports (/snap/storjshare/36/lib/node_modules/storjshare-daemon/node_modules/editor/index.js:15:14)
    at Object.<anonymous> (/snap/storjshare/36/lib/node_modules/storjshare-daemon/bin/storjshare-create.js:192:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

### Steps to Reproduce

see above. My default editor is `nano` as set in the environment variables `VISUAL` and `EDITOR`.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
