### ISSUE TITLE
30 reps:  Error:  Failed to join network

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-daemon#40]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
 * daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2


```

### Expected Behavior

Nodes continue to run.

### Actual Behavior

Node routinely crashing with error message "Failed to join network"

Full log attached.
```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...
[node00.zip](https://github.com/Storj/storjshare-daemon/files/715560/node00.zip)

**Comment by bookchin** [comment]
I think this belongs in the core repository.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Failed to join the network
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:278:28
    at done (/usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:2707:17)
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:356:16
    at replenish (/usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:877:25)
    at iterateeCallback (/usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:867:17)
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:840:16
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/async/dist/async.js:2720:21
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:270:11
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/lib/node.js:128:14
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:541:30
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/lib/router.js:539:14
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/lib/router.js:234:14
    at done (/usr/lib64/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:132:19)
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/node_modules/async/lib/async.js:32:16
    at /usr/lib64/node_modules/storjshare-daemon/node_modules/kad/lib/router.js:225:7
    at Object.callback (/usr/lib64/node_modules/storjshare-daemon/node_modules/kad/lib/router.js:265:14)
```
