### ISSUE TITLE
rpc.save is not a function

### ISSUE THREAD

**Issue by CJClaude** [Storj/storjshare-daemon#42]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
  * daemon: 2.1.2, core: 6.0.15, protocol: 1.1.0

```

Replace the values below using the output from `node --version`.

```
6.9.2
```

### Expected Behavior

storjshare save command should always work

### Actual Behavior

```
storj@i5serv ~ $ storjshare save
/usr/lib64/node_modules/storjshare-daemon/bin/storjshare-save.js:31
  rpc.save(storjshare_save.snapshot, (err) => {
      ^

TypeError: rpc.save is not a function
    at D.<anonymous> (/usr/lib64/node_modules/storjshare-daemon/bin/storjshare-save.js:31:7)
    at emitTwo (events.js:106:13)
    at D.emit (events.js:191:7)
    at Proto.<anonymous> (/usr/lib64/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:53:14)
    at emitOne (events.js:96:13)
    at Proto.emit (events.js:188:7)
    at Proto.handleMethods (/usr/lib64/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:118:10)
    at Proto.handle (/usr/lib64/node_modules/storjshare-daemon/node_modules/dnode-protocol/index.js:77:14)
    at D.dnode.handle (/usr/lib64/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/usr/lib64/node_modules/storjshare-daemon/node_modules/dnode/lib/dnode.js:106:22)

Since I've successfully used save before (on a different machine), my guess is this is realted to one share being stopped...

storj@i5serv ~ $ storjshare status

┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ acd0979d5f30adf78ee916089728c30ed9fbf1f4    │ running  │ 40m 41s  │ 15       │ 155      │ 564.8MB  │
│   → /storj/node03                           │          │          │          │          │ (2%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 11101de0a7edef3348c043ce4296f91261d1e747    │ stopped  │ 55m 5s   │ 30       │ 78       │ 16.71MB  │
│   → /storj/node00                           │          │          │          │          │ (0%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0842ead3a1e08f72032792ea0fc30bdbfc5d2a15    │ running  │ 41m 4s   │ 14       │ 160      │ 584.11MB │
│   → /storj/node01                           │          │          │          │          │ (2%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 065428feab8f78f887d45196a53f9f4c2768de59    │ running  │ 41m 4s   │ 12       │ 180      │ 327.02MB │
│   → /storj/node02                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0657b98c8b22112847abdd66d529c08de1675576    │ running  │ 41m 4s   │ 11       │ 181      │ 301.42MB │
│   → /storj/node04                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ cf64503c959b1240c73ff516e3e878954e94fa46    │ running  │ 40m 8s   │ 13       │ 162      │ 408.19MB │
│   → /storj/node05                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ b05c859969f4611c66fdb84438ab746b15406e4e    │ running  │ 41m 15s  │ 17       │ 147      │ 2MB      │
│   → /storj/node06                           │          │          │          │          │ (0%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ ed30be8d70025ed00d2f8fc57f599e7e20015d93    │ running  │ 41m 36s  │ 10       │ 162      │ 285.33MB │
│   → /storj/node07                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ f100019c3598566f32cf0e4331f1df9a0af33e28    │ running  │ 41m 4s   │ 13       │ 145      │ 3.46MB   │
│   → /storj/node08                           │          │          │          │          │ (0%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ d717d514b327f6211d53dc653c5111a02a32feef    │ running  │ 41m 15s  │ 14       │ 144      │ 320.89MB │
│   → /storj/node09                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 1fa56da183e0f58d0ffc465559e32f6315a15473    │ running  │ 41m 15s  │ 8        │ 160      │ 463.15MB │
│   → /storj/node10                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ e985c145e425bb61566676780d4631a88d8726f9    │ running  │ 41m 10s  │ 14       │ 148      │ 78.55MB  │
│   → /storj/node11                           │          │          │          │          │ (0%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ e6c88b300873c92a831d4e8770bf13285b8c638e    │ running  │ 40m 8s   │ 17       │ 146      │ 288.68MB │
│   → /storj/node12                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 3291d205b786bfdd33e814be63f4a771244b77ba    │ running  │ 41m 39s  │ 13       │ 163      │ 246.99MB │
│   → /storj/node13                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ b98858b98cf851103485d4de4eb33bfd58b0b269    │ running  │ 41m 39s  │ 12       │ 164      │ 190.25MB │
│   → /storj/node14                           │          │          │          │          │ (1%)     │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ ab62b2de9aa7ae04925700d1f2423129543e55db    │ running  │ 40m 54s  │ 12       │ 154      │ 284.02MB │
│   → /storj/node15                           │          │          │          │          │ (1%)     │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
This has been reported before. If you upgrade the daemon, you have to restart it with `storjshare killall && storjshare load` otherwise the old code is still running in the daemon process and the new code is running in the CLI.
