### ISSUE TITLE
TypeError: Cannot read property '_options' of undefined

### ISSUE THREAD

**Issue by subwolf** [Storj/storjshare-daemon#48]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.1.0, core: 6.0.14, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
7.4.0
```

### Expected Behavior

Everything runs as normal.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"replying to message to cccdf4d7e72c4e9b733fa81b3c2e38f9df7926a9","timestamp":"2017-01-24T09:38:03.408Z"}
/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/manager.js:212
  if (this._options.disableReaper) {
          ^

TypeError: Cannot read property '_options' of undefined
    at StorageManager._initShardReaper (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/manager.js:212:11)
    at Readable.<anonymous> (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/manager.js:178:5)
    at emitNone (events.js:86:13)
    at Readable.emit (events.js:185:7)
    at endReadableNT (/usr/lib/node_modules/storjshare-daemon/node_modules/readable-stream/lib/_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Just let it run.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/629

Fixed in core v6.0.15

I am not allowed to close the issue :(
