### ISSUE TITLE
Storjshare-daemon crash (under Mac OSX)

### ISSUE THREAD

**Issue by babonet13** [Storj/storjshare-daemon#50]
I'm running storjshare-daemon 2.1.2 under OXS Sierra.
II'm using the storjshare-load command in order to load my (meta)-configuration ...
daemon starting, then It crashes.
When I invoke the storjshare status command I've got this error message  :

==========================================

MacMini-de-Admin:~ Administrateur$ storjshare status
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENFILE: file table overflow, open '/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/lib/uri.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Administrateur/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-daemon/node_modules/bitcore-lib/index.js:57:15)

**Comment by bookchin** [comment]
Try http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

**Comment by bookchin** [comment]
Sort of related https://github.com/karma-runner/karma/issues/1979

**Comment by braydonf** [comment]
Seems stale now, please reopen if still an issue.
