### ISSUE TITLE
Deamon Unhandled 'error' event

### ISSUE THREAD

**Issue by Coinpiet** [Storj/storjshare-daemon#81]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.4.4, core: 6.2.1, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.5
```

### Expected Behavior

Please describe the program's expected behavior.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
{"level":"info","message":"replying to message to 75389b80e94c64c01e5015c8352a72bd09ef7f72","timestamp":"2017-02-28T19:41:53.975Z"}
{"level":"info","message":"destroying shard/contract for f7b043b3daff19192c4077463ab8b0d276029356","timestamp":"2017-02-28T19:41:59.287Z"}
{"level":"info","message":"flushing shards, some buckets will be inaccessible","timestamp":"2017-02-28T19:42:02.480Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\readable-stream\lib\_stream_readable.js:198:15)
    at Readable.push (C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\readable-stream\lib\_stream_readable.js:176:10)
    at C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\storj-lib\lib\storage\adapter.js:201:22
    at C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\storj-lib\lib\storage\adapter.js:83:5
    at C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\storj-lib\lib\storage\adapters\embedded.js:106:5
    at C:\Users\Peter\AppData\Roaming\npm\node_modules\storjshare-daemon\node_modules\levelup\lib\levelup.js:230:7
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run daemon 2.4.4
2. ...
3. ...

**Comment by littleskunk** [comment]
Duplicate and already fixed: https://github.com/Storj/core/issues/664
