### ISSUE TITLE
Exception causing a node to stop running

### ISSUE THREAD

**Issue by jcatania92** [Storj/storjshare-daemon#86]
**Package Versions**

Replace the values below using the output from storjshare --version.

daemon: 2.5.0, 
core: 6.3.0, 
protocol: 1.1.0

Replace the values below using the output from node --version.

v6.10.0

After running for a while at random time I am getting the below error which causes the node to stop running. The only solution to solve this is to restart it.

{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.380Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.612Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.650Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.866Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-04T17:57:19.919Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

**Comment by littleskunk** [comment]
Full logfile please

**Comment by littleskunk** [comment]
Thank you for sending me the logfile on rocket chat.
```
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.076Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.098Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.114Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.261Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.277Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.296Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.430Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.461Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.461Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.599Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.646Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.662Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.778Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.831Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.847Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:28.963Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.000Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.016Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.132Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.179Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.201Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.317Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.399Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.402Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.517Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.564Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.580Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.698Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.749Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.749Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.881Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.934Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:29.934Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:30.050Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:30.103Z"}
{"level":"warn","message":"maximum tunnel sockets enhausted","timestamp":"2017-03-06T06:35:30.103Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
{"level":"warn","message":"your address is public and traversal strategies are disabled","timestamp":"2017-03-06T19:23:15.687Z"}
```

You don't use a tunnel connection. How many tunnel connection do you OFFER to other farmer? It looks like there is an issue on the tunnel server side.

Another user with the same problem:
> After nearly fifteen days of running 1313 Storjshare-daemons (tunnel mode only) : 
> - 461 restarts (71 daemons has restarted more than one time)
> Th3Van on rocket chat

**Comment by littleskunk** [comment]
Can be closed. Moved to https://github.com/Storj/core/issues/676

**Comment by jcatania92** [comment]
Thank you.
