### ISSUE TITLE
Error with google-drive-ocamlfuse on restart

### ISSUE THREAD

**Issue by ne0ark** [Storj/storjshare-daemon#99]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
daemon: 2.5.0, core: 6.3.0, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Start the config file.

### Actual Behavior

Status shows multiple restart and farm doesn't start.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install google-drive-ocamlfuse
2. Killall and try to restart

Error:

```
tail -50 e1ac09725fbf507c3813caf6c8fd6a64b87eba47.log
at Object. (/usr/lib/node_modules/storjshare-daemon/script/farmer.js:24:3)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3

assert.js:85
throw new assert.AssertionError({
^
AssertionError: Table path is not a valid KFS instance
at Btable._validateTablePath (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:97:7)
at Btable._open (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:62:12)
at new Btable (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/lib/b-table.js:51:10)
at module.exports (/usr/lib/node_modules/storjshare-daemon/node_modules/kfs/index.js:15:34)
at new EmbeddedStorageAdapter (/usr/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/storage/adapters/embedded.js:30:14)
at Object. (/usr/lib/node_modules/storjshare-daemon/script/farmer.js:24:3)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
```
Please see: https://github.com/Storj/kfs/issues/52

**Comment by bookchin** [comment]
Please check your configuration for the storage path and make sure that the drive is accessible at that path. This assertion error is stating that it is not.

**Comment by bookchin** [comment]
Also, I do not recommended using a network mounted google drive to store shards and lean very strong towards "we don't support that".

**Comment by ne0ark** [comment]
Yes drive is accessible to that path. I can ls and upload a test file.

**Comment by ne0ark** [comment]
This only seem to happen if killall is used before restarting. This error doesn't happen on stopping first and then killall.

**Comment by bookchin** [comment]
The `killall` command is not a clean shutdown, use `stop` unless you have a good reason to not do so.

**Comment by Altosaxophony** [comment]
> The killall command is not a clean shutdown, use stop unless you have a good reason to not do so.

I know this is OT. But how should the user know? Please have a look at the following output

```
storjshare-killall --help

  Usage: storjshare-killall [options]

  destroys all running shares and stop daemon
```

I just wrote because i am confused now, not want to diss you.

**Comment by bookchin** [comment]
Might be a good opportunity for someone to submit a PR updating the help text. Closing since it seems that @ne0ark has affirmed that a clean stop will not cause this issue.
